In [16]:
__author__ = 'Dennis Strik'

#Import of different libraries
import matplotlib.pyplot as plt
plt.style.use('bmh')

import matplotlib.lines as mlines
from shapely.geometry import Polygon #Module for manipulation and analysis of geometric objects in the Cartesian plane.
import pandas as pd #This module provides high-performance, easy-to-use data structures and data analysis tools for Python
from shapely.geometry import Point #The Point constructor takes positional coordinate values or point tuple parameters to create a single point.
import numpy as np
from geopy import distance

Deze declaratie van ankervakken is naar voren gehaald, veranderd van een tuple naar een dict en er is een item report toegevoegd, waar straks per ankervak de meldingen in komen.

In [17]:
# Creation of the polygon of the Ankervakken and put them in an array for iteration.
Ankervak1 = {'name':'Ankervak1', 'report': list() , 'area': Polygon([(2.754580,52.134195),(2.868095, 52.134758),(2.774023, 52.067847), (2.710605,52.065838), (2.713578,52.099202)])}
Ankervak2 ={'name':'Ankervak2', 'report': list() , 'area': Polygon([(2.860076,51.918421),(2.921510,51.942252),(3.001128,51.949211),(2.877470,51.901307)])}
Ankervak3N = {'name':'Ankervak3N', 'report': list()  , 'area': Polygon([(3.139327,52.017562),(3.209322,52.021018),(3.231510,51.998010),(3.137953,51.990032)])}
Ankervak3S = {'name':'Ankervak3S', 'report': list()  , 'area': Polygon([(3.131148,51.948142),(3.225792,51.956233),(3.204232,51.927322),(3.125773,51.917598)])}
Ankervak3E = {'name':'Ankervak3E', 'report': list()  , 'area': Polygon([(3.455220,52.031497),(3.556038,52.035870),(3.558498,52.009482),(3.450245,52.000552)])}
Ankervak4W = {'name':'Ankervak4W', 'report': list()  , 'area': Polygon([(3.404835,51.901690),(3.629159,51.944325),(3.643326,51.916664),(3.412613,51.874399)])}
Ankervak4E = {'name':'Ankervak4E', 'report': list()  , 'area': Polygon([(3699690,51.953512),(3812517,51.959837),(3818178,51.921983),(3705352,51.915653)])}
Ankervak5 = {'name':'Ankervak5', 'report': list()  , 'area': Polygon([(3.544315,52.182028),(3.746525,52.181712),(3.744408,52.118780),(3.637528,52.118217),(3.543915,52.151260)])}
Ankervak6 = {'name':'Ankervak6', 'report': list()  , 'area': Polygon([(3.725538,52.459422),(3.824412,52.467875),(3.817720,52.447125),(3.730055,52.439647)])}
Ankervak7 = {'name':'Ankervak7', 'report': list()  , 'area': Polygon([(3.907160,52.425455),(3.958340,52.442512),(4.149455,52.471437),(4.158833,52.458130),(4.034970,52.438108),(4.019700,52.422518),(3.904643,52.417658)])}
Ankervak8 = {'name':'Ankervak8', 'report': list()  , 'area': Polygon([(4.206183,52.540493),(4.339370,52.527555),(4.356640,52.506660),(4.220823,52.522498)])}

Ankervak_Schouwenbank = {'name':'AnkervakSchouwenbank', 'report': list()  , 'area': Polygon([(03.278667,51.770848),(03.305343,51.744172),(03.4065,51.800500),(03.395935,51.837335)])}
Ankervak_ScheveningenA = {'name':'AnkervakScheveningenA', 'report': list()  , 'area': Polygon([(4.223682,52.215868),(4.257022,52.194190),(4.218650,52.165855),(4.195318,52.196720)])}
Ankervak_ScheveningenB = {'name':'AnkervakScheveningenB', 'report': list()  , 'area': Polygon([(4.253992,52.134195),(4.260682,52.125855),(4.247015,52.121877),(4.242040,52.131697)])}

Ankervakken = [Ankervak1, Ankervak2, Ankervak3N, Ankervak3S, Ankervak3E, Ankervak4E, Ankervak4W, Ankervak5, Ankervak6, \
               Ankervak7, Ankervak8, Ankervak_Schouwenbank, Ankervak_ScheveningenA, Ankervak_ScheveningenB]

Hier is de read_csv uitgehaald, die is verplaats naar de iterator een blok daar beneden

In [18]:
# Sprecify the file location here
#filename0 = 'C:\\Users\\marisa\\Documents\\Kustwacht\\testSmall.csv'
#filename0a = 'C:\\Users\\marisa\\Documents\\Kustwacht\\db_20170401_00-00_20170409_23-59_int_30.csv'
filename1 = '/Users/jasper/Documents/Rfiles/IDLab/Ankervakken/Bronnen/db_20170401_00-00_20170409_23-59_int_30.csv.zip'
filename2 = '/Users/jasper/Documents/Rfiles/IDLab/Ankervakken/Bronnen/db_20170410_00-00_20170419_23-59_int_30.csv.zip'
filename3 = '/Users/jasper/Documents/Rfiles/IDLab/Ankervakken/Bronnen/db_20170420_00-00_20170430_23-59_int_30.csv.zip'
filename4 = '/Users/jasper/Documents/Rfiles/IDLab/Ankervakken/Bronnen/db_20170501_00-00_20170531_23-59_int_30.csv.zip'
#filename4 = 'F:\\AIS KWC export april 2017\\db_20170601_00-00_20170630_23-59_int_30.csv.zip'
#df = pd.read_csv(filename1)

Dit is de grote nieuw forloop die inleest, cleaned, kijkt of ze in het ankervak vallen en dan toevoegd aan de juist dict in 'Ankervakken'

In [ ]:
%%time
for df in pd.read_csv(filename4, iterator=True, chunksize=1e8):
    # Creation of a new dataframe df_new without the less relevant columns
    systemID = df.iloc[:,0:1]
    name_lat_long = df.iloc[:,6:9]
    imo = df.iloc[:,33:34]
    t_init = df.iloc[:,1:2]
    t_update = df.iloc[:,2:3]
    mmsi = df.iloc[:,5:6]
    ves = df.iloc[:,40:41]
    des = df.iloc[:,30:31]
    speed = df.iloc[:,20:21]
    heading = df.iloc[:,21:22]
    length = df.iloc[:,11:12]
    navstatus = df.iloc[:,14:15]

    df_new = pd.concat([systemID, name_lat_long, imo, mmsi, ves, des, speed, heading, length, navstatus ,t_init, t_update, ],axis=1)
    df_new.columns = ['SystemID', 'Name', 'Lat', 'Lon', 'IMO', 'MMSI', 'Schiptype', 'Destination', 'Speed', 'Heading', 'Length', "NavStatus", 'Starttime', 'Updatetime']
    
    df_new = df_new[np.isfinite(df_new['MMSI'])]
    df_new['Starttime'] = df_new['Starttime'].astype('datetime64[ns]')
    df_new['Updatetime'] = df_new['Updatetime'].astype('datetime64[ns]')
    
    for n in range(0, len(df_new)):
        la = df_new.iloc[n,2]
        lo = df_new.iloc[n,3]
        coordAsPoint = Point(lo, la)
        for avak in Ankervakken:
            if(avak['area'].contains(coordAsPoint)):
                avak['report'].append(df_new.iloc[n,:])

Onderstaan schrijven we de dicts om naar dataframes en voegen de naam van de ankervakken toe

In [7]:
%%time
for avak in Ankervakken:
#    print(avak)
    labels = ['SystemID', 'Name', 'Lat', 'Lon', 'IMO', 'MMSI', 'Schiptype', 'Destination', 'Speed', 'Heading', 'Length', "NavStatus", 'Starttime', 'Updatetime']
    avak['report'] = pd.DataFrame.from_records([s.to_dict() for s in avak['report']])
    
    avak['report']['ankervak'] = avak['name']

CPU times: user 15.7 s, sys: 335 ms, total: 16.1 s
Wall time: 16.1 s

In [8]:
#%%time
#het toevoegen van alle geselecteerde schepen naar 1 dict en die sorteren op Updatetime
AllSchipinankervak = pd.DataFrame()
for dframe in Ankervakken:
    AllSchipinankervak= AllSchipinankervak.append(dframe['report'], ignore_index = True, sort = False)

AllSchipinankervak.sort_values('Updatetime')

,Destination,Heading,IMO,Lat,Length,Lon,MMSI,Name,NavStatus,Schiptype,Speed,Starttime,SystemID,Updatetime,ankervak
535924,STELLENDAM,229.2,8008371.0,52.194729,24.0,4.221396,245617000.0,ADRIANNE OD3,7.0,30.0,2.3,2017-04-19 23:56:21.299,2.017042e+18,2017-04-20 00:00:00.296,AnkervakScheveningenA
333494,STEENBANK,NaN,9344203.0,51.795521,86.9,3.370080,215389000.0,M/T GOVIKEN,1.0,80.0,0.0,2017-04-19 15:44:47.478,2.017042e+18,2017-04-20 00:00:02.309,AnkervakSchouwenbank
54801,ROTTERDAM,NaN,9538658.0,51.917801,299.8,3.627570,636092485.0,HS ROME,1.0,70.0,0.0,2017-04-19 23:14:53.326,2.017042e+18,2017-04-20 00:00:02.309,Ankervak4W
104945,ROTTERDAM,NaN,9257022.0,52.173931,239.3,3.595300,538006093.0,RIDGEBURY ALICE M,1.0,80.0,0.0,2017-04-19 15:44:47.495,2.017042e+18,2017-04-20 00:00:02.309,Ankervak5
333495,GHENT,NaN,9401556.0,51.783531,144.5,3.356260,259936000.0,STAV VIKING,1.0,80.0,0.0,2017-04-19 21:28:47.312,2.017042e+18,2017-04-20 00:00:02.309,AnkervakSchouwenbank
104946,FISHINGGROUNDS,289.3,9073878.0,52.132904,44.0,3.657344,244020352.0,SCH 63 QUO VADIS,7.0,30.0,2.5,2017-04-19 22:03:02.316,2.017042e+18,2017-04-20 00:00:02.783,Ankervak5
7683,ROTTERDAM,182.1,9460655.0,51.937658,292.0,2.938050,566064000.0,TRUST AGILITY,1.0,70.0,0.1,2017-04-19 22:42:35.312,2.017042e+18,2017-04-20 00:00:08.312,Ankervak2
535925,SCHEVENINGEN,NaN,9313527.0,52.199181,148.2,4.201080,235011030.0,GIJON KNUTSEN,1.0,80.0,0.0,2017-04-19 18:31:57.288,2.017042e+18,2017-04-20 00:00:15.296,AnkervakScheveningenA
104947,ANCHORAGE,NaN,9432490.0,52.167511,108.4,3.700760,235070364.0,NOMADIC BERGEN,1.0,70.0,0.0,2017-04-19 15:44:47.789,2.017042e+18,2017-04-20 00:00:17.797,Ankervak5
333496,ANTWERPEN,NaN,9328649.0,51.774181,154.3,3.297480,305654000.0,ALEXANDER B,1.0,70.0,0.0,2017-04-19 15:44:47.471,2.017042e+18,2017-04-20 00:00:20.311,AnkervakSchouwenbank
333497,STEENBANK PILOT STAT,NaN,9260407.0,51.793442,119.1,3.322260,255623000.0,AMARANT,1.0,80.0,0.0,2017-04-19 15:44:47.475,2.017042e+18,2017-04-20 00:00:20.311,AnkervakSchouwenbank
333498,STEENBANK PILOT,NaN,9174713.0,51.778320,99.6,3.309340,210607000.0,AMBER 1,1.0,80.0,0.0,2017-04-19 21:50:59.334,2.017042e+18,2017-04-20 00:00:20.311,AnkervakSchouwenbank
535926,SCHEVENINGEN ANCH,NaN,9312080.0,52.188808,89.9,4.218810,249231000.0,PATAGONIA,1.0,80.0,0.0,2017-04-19 23:43:27.286,2.017042e+18,2017-04-20 00:00:21.297,AnkervakScheveningenA
333500,ANTWERP,NaN,9720483.0,51.816528,299.8,3.370500,255805855.0,MSC CHLOE,1.0,70.0,0.0,2017-04-19 15:44:47.478,2.017042e+18,2017-04-20 00:00:26.308,AnkervakSchouwenbank
333499,BEANR,NaN,9220079.0,51.803951,159.2,3.387940,538001652.0,SANDY RICKMERS,1.0,70.0,0.0,2017-04-19 15:44:47.478,2.017042e+18,2017-04-20 00:00:26.308,AnkervakSchouwenbank
104948,ANCHORAGE MAAS 5,NaN,9488322.0,52.138851,128.9,3.655300,215760000.0,PECHORA STAR,1.0,80.0,0.0,2017-04-19 15:44:47.506,2.017042e+18,2017-04-20 00:00:26.308,Ankervak5
54802,NaN,20.3,NaN,51.883433,200.2,3.450001,538006304.0,VICTORIA,1.0,NaN,0.1,2017-04-19 23:27:29.312,2.017042e+18,2017-04-20 00:00:26.308,Ankervak4W
535927,STELLENDAM,229.9,8008371.0,52.194330,24.0,4.220594,245617000.0,ADRIANNE OD3,7.0,30.0,2.3,2017-04-19 23:56:21.299,2.017042e+18,2017-04-20 00:00:30.301,AnkervakScheveningenA
104950,FISHINGGROUNDS,291.6,9073878.0,52.133163,44.0,3.656382,244020352.0,SCH 63 QUO VADIS,7.0,30.0,2.5,2017-04-19 22:03:02.316,2.017042e+18,2017-04-20 00:00:32.324,Ankervak5
104949,ROTTERDAM ANCH.,NaN,9234628.0,52.148689,168.0,3.580750,236204000.0,APOLLO,1.0,80.0,0.0,2017-04-19 19:33:59.325,2.017042e+18,2017-04-20 00:00:32.324,Ankervak5
333501,ANTWERP,NaN,8201636.0,51.781490,203.1,3.337590,357562000.0,MSC MALIN,1.0,70.0,0.0,2017-04-19 15:44:47.475,2.017042e+18,2017-04-20 00:00:41.322,AnkervakSchouwenbank
333503,NaN,NaN,NaN,51.759392,116.2,3.330710,229972000.0,WISBY WAVE,1.0,NaN,0.0,2017-04-19 21:05:17.324,2.017042e+18,2017-04-20 00:00:41.322,AnkervakSchouwenbank
0,OPL ROTTERDAM,NaN,9260005.0,52.099239,183.0,2.766149,229388000.0,SEAMERCURY,1.0,80.0,0.0,2017-04-19 23:58:38.311,2.017042e+18,2017-04-20 00:00:41.322,Ankervak1
333502,ANTWERPEN,NaN,9112870.0,51.771488,99.6,3.347180,244085000.0,DUTCH SPIRIT,1.0,80.0,0.0,2017-04-19 15:44:47.477,2.017042e+18,2017-04-20 00:00:41.322,AnkervakSchouwenbank
104951,MAAS ANCH 5,134.4,9360972.0,52.124256,126.0,3.655776,255805836.0,DANCE,1.0,70.0,0.2,2017-04-19 20:49:11.325,2.017042e+18,2017-04-20 00:00:44.783,Ankervak5
104952,ROTTERDAM ANCHOREG 5,194.7,9290505.0,52.150366,182.6,3.688018,538090265.0,MARE AMBASSADOR,1.0,80.0,0.2,2017-04-19 21:29:38.325,2.017042e+18,2017-04-20 00:00:50.797,Ankervak5
32462,NaN,NaN,NaN,51.943611,246.1,3.196970,371325000.0,BALTIC GALAXY,1.0,NaN,0.0,2017-04-19 23:05:17.311,2.017042e+18,2017-04-20 00:00:53.322,Ankervak3S
27186,ROTTERDAM,NaN,9634701.0,52.013069,299.8,3.193670,256848000.0,FAKARAVA,1.0,70.0,0.0,2017-04-19 22:53:02.315,2.017042e+18,2017-04-20 00:00:59.321,Ankervak3N
333504,ANTWERP,149.1,9720483.0,51.816358,299.8,3.370623,255805855.0,MSC CHLOE,1.0,70.0,0.2,2017-04-19 15:44:47.478,2.017042e+18,2017-04-20 00:00:59.321,AnkervakSchouwenbank
535928,STELLENDAM,230.7,8008371.0,52.193929,24.0,4.219797,245617000.0,ADRIANNE OD3,7.0,30.0,2.3,2017-04-19 23:56:21.299,2.017042e+18,2017-04-20 00:01:00.296,AnkervakScheveningenA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
535916,SCHOUWENBANK ?,NaN,9112882.0,51.768558,99.6,3.345530,244281000.0,DUTCH FAITH,1.0,80.0,0.0,2017-04-30 18:44:14.328,2.017043e+18,2017-04-30 23:58:53.327,AnkervakSchouwenbank
312620,ROTTERDAM,246.3,9346500.0,52.131919,88.9,3.687137,257941000.0,NORDIC SIRA,1.0,80.0,0.1,2017-04-30 18:13:15.787,2.017043e+18,2017-04-30 23:58:56.800,Ankervak5
104941,ROTTERDAM,NaN,9724532.0,51.917881,182.6,3.530510,235113757.0,BRITISH CUMULUS,1.0,80.0,0.0,2017-04-30 02:50:11.327,2.017043e+18,2017-04-30 23:58:59.326,Ankervak4W
54799,SCHEVENINGEN,89.7,9085182.0,52.019601,14.5,3.551443,244399000.0,UK149 STELLA MARIS,7.0,30.0,2.5,2017-04-30 05:25:17.801,2.017043e+18,2017-04-30 23:59:02.312,Ankervak3E
312623,PET 1 KO,222.3,9327205.0,52.145606,92.8,3.709572,215964000.0,TROY,0.0,90.0,0.6,2017-04-30 20:12:11.802,2.017043e+18,2017-04-30 23:59:02.796,Ankervak5
329850,AMSTERDAM -NLAMS,NaN,9384136.0,52.428082,184.0,3.981830,247243900.0,VALTELLINA,1.0,80.0,0.0,2017-04-30 22:17:08.788,2.017043e+18,2017-04-30 23:59:02.796,Ankervak7
312622,ROTTERDAM,NaN,9753818.0,52.172119,108.4,3.588890,256831000.0,SAN BACCO,1.0,80.0,0.0,2017-04-30 18:51:29.788,2.017043e+18,2017-04-30 23:59:02.796,Ankervak5
312621,RTM ANC5,NaN,9391414.0,52.160912,183.6,3.678900,636091633.0,CONTI HUMBOLDT,1.0,80.0,0.0,2017-04-30 17:59:38.788,2.017043e+18,2017-04-30 23:59:02.796,Ankervak5
329851,AMSTERDAM,NaN,9396799.0,52.421841,182.0,3.932240,538003115.0,SUNNY BAY,1.0,80.0,0.0,2017-04-30 22:41:41.788,2.017043e+18,2017-04-30 23:59:14.783,Ankervak7
104942,NaN,NaN,NaN,51.889931,200.2,3.481770,249319000.0,ADAM ASNYK,1.0,NaN,0.0,2017-04-30 12:00:14.329,2.017043e+18,2017-04-30 23:59:20.326,Ankervak4W
535917,STEENBANK ANC.,NaN,9344203.0,51.783810,86.9,3.363590,215389000.0,M/T GOVIKEN,1.0,80.0,0.0,2017-04-30 14:42:41.328,2.017043e+18,2017-04-30 23:59:20.326,AnkervakSchouwenbank
312624,FOR ORDER,184.7,9106912.0,52.124028,87.9,3.652280,304036000.0,HAV PIKE,1.0,70.0,0.2,2017-04-30 19:14:23.799,2.017043e+18,2017-04-30 23:59:20.783,Ankervak5
535918,NaN,150.8,NaN,51.790597,117.2,3.378163,245911000.0,STELLA POLARIS,1.0,NaN,0.2,2017-04-29 23:12:05.316,2.017043e+18,2017-04-30 23:59:23.324,AnkervakSchouwenbank
333493,BY ORDER,82.5,9233624.0,52.535420,34.4,4.221320,371043000.0,BARU SATU,1.0,70.0,0.2,2017-04-30 22:38:51.300,2.017043e+18,2017-04-30 23:59:24.283,Ankervak8
27185,ROTTERDAM,162.5,9288851.0,51.913179,366.6,2.884181,229272000.0,HS TOSCA,1.0,80.0,0.1,2017-04-30 00:03:53.329,2.017043e+18,2017-04-30 23:59:26.313,Ankervak2
535919,BEANR,NaN,9181663.0,51.767799,293.9,3.284980,353719000.0,MSC MATILDE,1.0,70.0,0.0,2017-04-29 11:50:32.327,2.017043e+18,2017-04-30 23:59:26.313,AnkervakSchouwenbank
312625,ROTTERDAM,185.4,9299898.0,52.140396,250.0,3.613429,240335000.0,PELAGOS,1.0,80.0,0.2,2017-04-30 21:46:56.786,2.017043e+18,2017-04-30 23:59:26.783,Ankervak5
535920,FOR ORDER,43.1,9350898.0,51.773371,108.4,3.354684,636016149.0,CORAL LACERA,1.0,80.0,0.2,2017-04-28 18:52:35.314,2.017043e+18,2017-04-30 23:59:29.327,AnkervakSchouwenbank
312626,FOR ORDERS,NaN,9298375.0,52.173721,164.1,3.677130,269848000.0,SCT BREITHORN,1.0,80.0,0.0,2017-04-30 19:51:50.789,2.017043e+18,2017-04-30 23:59:29.797,Ankervak5
54800,SCHEVENINGEN,90.7,9085182.0,52.019570,29.6,3.552577,244399000.0,UK149 STELLA MARIS,7.0,30.0,2.6,2017-04-30 05:25:17.801,2.017043e+18,2017-04-30 23:59:32.327,Ankervak3E
312629,ROTTERDAM,177.6,9299898.0,52.140286,250.0,3.613260,240335000.0,PELAGOS,1.0,80.0,0.2,2017-04-30 21:46:56.786,2.017043e+18,2017-04-30 23:59:32.783,Ankervak5
312628,ROTTERDAM,185.5,9327205.0,52.145484,92.8,3.709308,215964000.0,TROY,0.0,80.0,0.6,2017-04-30 20:12:11.802,2.017043e+18,2017-04-30 23:59:32.783,Ankervak5
312627,FOR ORDER,174.5,9106912.0,52.124016,87.9,3.652310,304036000.0,HAV PIKE,1.0,70.0,0.2,2017-04-30 19:14:23.799,2.017043e+18,2017-04-30 23:59:32.783,Ankervak5
535921,NaN,96.6,NaN,51.790630,117.2,3.378226,245911000.0,STELLA POLARIS,1.0,NaN,0.2,2017-04-29 23:12:05.316,2.017043e+18,2017-04-30 23:59:38.312,AnkervakSchouwenbank
535922,FOR ORDER,84.8,9350898.0,51.773350,108.4,3.354726,636016149.0,CORAL LACERA,1.0,80.0,0.2,2017-04-28 18:52:35.314,2.017043e+18,2017-04-30 23:59:41.325,AnkervakSchouwenbank
535923,NOMON>NLRTM,NaN,9259898.0,51.815922,182.6,3.391680,249344000.0,PINK CORAL,1.0,80.0,0.0,2017-04-30 23:07:59.331,2.017043e+18,2017-04-30 23:59:41.325,AnkervakSchouwenbank
104944,ROTTERDAM,NaN,9350343.0,51.899010,228.5,3.451300,538006052.0,PANAFRICAN,1.0,70.0,0.0,2017-04-30 21:40:08.333,2.017043e+18,2017-04-30 23:59:44.332,Ankervak4W
7682,DEEP WATER ANCHORAGE,NaN,9233234.0,52.094818,244.0,2.755689,237846000.0,MINERVA MAYA,1.0,80.0,0.0,2017-04-30 22:41:56.329,2.017043e+18,2017-04-30 23:59:44.332,Ankervak1
51855,ROTTERDAM,NaN,9438406.0,51.935032,274.4,3.178480,538003601.0,PENTATHLON,1.0,80.0,0.0,2017-04-30 20:32:47.331,2.017043e+18,2017-04-30 23:59:44.332,Ankervak3S
104943,NaN,NaN,NaN,51.896370,142.6,3.415590,246625000.0,VLIEBORG,1.0,NaN,0.0,2017-04-30 21:02:41.317,2.017043e+18,2017-04-30 23:59:44.332,Ankervak4W

In [10]:
# Het wegschrijven naar 1 dict
writefilename1 = '/Users/jasper/Documents/Rfiles/IDLab/Ankervakken/Bronnen/'+ '20170401-0409.csv'
writefilename2 = '/Users/jasper/Documents/Rfiles/IDLab/Ankervakken/Bronnen/'+ '20170410-0419.csv'
writefilename3 = '/Users/jasper/Documents/Rfiles/IDLab/Ankervakken/Bronnen/'+ '20170420-0430.csv'
writefilename4 = '/Users/jasper/Documents/Rfiles/IDLab/Ankervakken/Bronnen/'+ '20170501-0531.csv'
#writefilename5 = '/Users/jasper/Documents/Rfiles/IDLab/Ankervakken/Bronnen/'+ '20170601-0630.csv'
#print(writefilename4)

/Users/jasper/Documents/Rfiles/IDLab/Ankervakken/Bronnen/20170420-0430.csv

In [11]:
AllSchipinankervak.to_csv(writefilename4)

Onderstaande berekening is nog niet zo veel veranderd, wel wordt er gelooped over een andere dataframe, die net even anders aangeroepen wordt, zie comments in  de code

In [12]:
#even de min/max datum-tijd ophalen om in volgens cell goede grenzen te zetten
(min(AllSchipinankervak['Updatetime']), max(AllSchipinankervak['Updatetime']))

(Timestamp('2017-04-20 00:00:00.296000'),
 Timestamp('2017-04-30 23:59:44.332000'))

In [13]:
%%time
#creation of time range
#goed opletten hier wordt de timerange nog handmatig ingesteld!
prng = pd.date_range('04/20/2017 00:00:00', '05/01/2017 00:00:00', freq='5T').tolist()
idx = [np.random.randn(len(prng))]
dftimes = pd.DataFrame(prng, columns=['A'], index=idx)
dftimes['A'] = dftimes['A'].astype('datetime64[ns]')

dfresult = pd.DataFrame()

#deze loop maakt paren met schepen per ankervak
for avak in Ankervakken: #hier staat nu ankervakken
    df_out = avak['report'] # hier moeten we hem herbenoemen om niet de hele code om te schrijven
    if df_out.index.empty: # hier checken we op lege dataframes,
        continue

    mmsi = df_out['MMSI'].unique()
    mmsiDone = set()
    
    #tracker to inform of progress
    print(len(mmsi))
    
    for mnum1 in mmsi:
        df_temp1 = df_out[df_out['MMSI']==mnum1]
        df_new1 = pd.merge_asof(dftimes, df_temp1, left_on = 'A' , right_on='Updatetime', direction='nearest', tolerance=pd.Timedelta('20m'))
        dist_to_vessels = dict()
        dist_to_vessels[mnum1] = dftimes.copy()
        name1 =  df_new1['Name'].unique()
        mmsiDone.add(mnum1)
        
        
        for mnum2 in mmsi:
            if mnum2 == mnum1:
                continue
            if mnum2 in mmsiDone:
                continue
            else:
                df_temp2 = df_out[df_out['MMSI']==mnum2]
                df_new2 = pd.merge_asof(dftimes, df_temp2, left_on = 'A' , right_on='Updatetime', direction='nearest', tolerance=pd.Timedelta('20m'))
                clms = ['time', 'Name1', 'MMSI1', 'Name2', 'MMSI2', 'Distance', 'Ankervak']
                resultTemp = pd.DataFrame(columns= clms)
                distances = []
                name2 = df_new2['Name'].unique()

                for i in range(len(dftimes)):
                    if np.isfinite([df_new1['Lat'][i], df_new1['Lon'][i], df_new2['Lat'][i], df_new2['Lon'][i]]).all():
                        point1 = (df_new1['Lat'][i], df_new1['Lon'][i])
                        point2 = (df_new2['Lat'][i], df_new2['Lon'][i])
                        dist = distance.geodesic(point1, point2).nautical
                        distances.append(dist)
                        line = {'time': df_new1['A'][i], 'Name1': name1[0], 'MMSI1':mnum1, 'Name2': name2[0],\
                                          'MMSI2': mnum2 ,'Distance': dist, 'Ankervak': df_new1['ankervak'][i] }
                        resultTemp = resultTemp.append(line, ignore_index = True)
                        
                if len(distances)>0:
                    if min(distances) < 0.4:
#                     resultTemp.plot('time', 'Distance', title = str(name1[0]) + ' - '+ str(name2[0]))
                        dfresult = pd.concat([dfresult, resultTemp], axis = 0, ignore_index = True)               

# plt.show()

30
65
9
14
16
84
129
40
81
151
145
52
44
CPU times: user 2h 2min 47s, sys: 14.2 s, total: 2h 3min 1s
Wall time: 3h 28min 30s

In [14]:
writefilename1 = '/Users/jasper/Documents/Rfiles/IDLab/Ankervakken/Bronnen/'+ 'distances201704010409.csv'
writefilename2 = '/Users/jasper/Documents/Rfiles/IDLab/Ankervakken/Bronnen/'+ 'distances201704100419.csv'
writefilename3 = '/Users/jasper/Documents/Rfiles/IDLab/Ankervakken/Bronnen/'+ 'distances201704200430.csv'
writefilename4 = '/Users/jasper/Documents/Rfiles/IDLab/Ankervakken/Bronnen/'+ 'distances201705010531.csv'
writefilename5 = '/Users/jasper/Documents/Rfiles/IDLab/Ankervakken/Bronnen/'+ 'distances201706010630.csv'

In [15]:
dfresult.to_csv(writefilename3)