In [1]:
__author__ = 'Dennis Strik'

#Import of different libraries
import matplotlib.pyplot as plt
plt.style.use('bmh')

import matplotlib.lines as mlines
from shapely.geometry import Polygon #Module for manipulation and analysis of geometric objects in the Cartesian plane.
import pandas as pd #This module provides high-performance, easy-to-use data structures and data analysis tools for Python
from shapely.geometry import Point #The Point constructor takes positional coordinate values or point tuple parameters to create a single point.
import numpy as np
from geopy import distance

Deze declaratie van ankervakken is naar voren gehaald, veranderd van een tuple naar een dict en er is een item report toegevoegd, waar straks per ankervak de meldingen in komen.

In [2]:
# Creation of the polygon of the Ankervakken and put them in an array for iteration.
Ankervak1 = {'name':'Ankervak1', 'report': list() , 'area': Polygon([(2.754580,52.134195),(2.868095, 52.134758),(2.774023, 52.067847), (2.710605,52.065838), (2.713578,52.099202)])}
Ankervak2 ={'name':'Ankervak2', 'report': list() , 'area': Polygon([(2.860076,51.918421),(2.921510,51.942252),(3.001128,51.949211),(2.877470,51.901307)])}
Ankervak3N = {'name':'Ankervak3N', 'report': list()  , 'area': Polygon([(3.139327,52.017562),(3.209322,52.021018),(3.231510,51.998010),(3.137953,51.990032)])}
Ankervak3S = {'name':'Ankervak3S', 'report': list()  , 'area': Polygon([(3.131148,51.948142),(3.225792,51.956233),(3.204232,51.927322),(3.125773,51.917598)])}
Ankervak3E = {'name':'Ankervak3E', 'report': list()  , 'area': Polygon([(3.455220,52.031497),(3.556038,52.035870),(3.558498,52.009482),(3.450245,52.000552)])}
Ankervak4W = {'name':'Ankervak4W', 'report': list()  , 'area': Polygon([(3.404835,51.901690),(3.629159,51.944325),(3.643326,51.916664),(3.412613,51.874399)])}
Ankervak4E = {'name':'Ankervak4E', 'report': list()  , 'area': Polygon([(3699690,51.953512),(3812517,51.959837),(3818178,51.921983),(3705352,51.915653)])}
Ankervak5 = {'name':'Ankervak5', 'report': list()  , 'area': Polygon([(3.544315,52.182028),(3.746525,52.181712),(3.744408,52.118780),(3.637528,52.118217),(3.543915,52.151260)])}
Ankervak6 = {'name':'Ankervak6', 'report': list()  , 'area': Polygon([(3.725538,52.459422),(3.824412,52.467875),(3.817720,52.447125),(3.730055,52.439647)])}
Ankervak7 = {'name':'Ankervak7', 'report': list()  , 'area': Polygon([(3.907160,52.425455),(3.958340,52.442512),(4.149455,52.471437),(4.158833,52.458130),(4.034970,52.438108),(4.019700,52.422518),(3.904643,52.417658)])}
Ankervak8 = {'name':'Ankervak8', 'report': list()  , 'area': Polygon([(4.206183,52.540493),(4.339370,52.527555),(4.356640,52.506660),(4.220823,52.522498)])}

Ankervak_Schouwenbank = {'name':'AnkervakSchouwenbank', 'report': list()  , 'area': Polygon([(03.278667,51.770848),(03.305343,51.744172),(03.4065,51.800500),(03.395935,51.837335)])}
Ankervak_ScheveningenA = {'name':'AnkervakScheveningenA', 'report': list()  , 'area': Polygon([(4.223682,52.215868),(4.257022,52.194190),(4.218650,52.165855),(4.195318,52.196720)])}
Ankervak_ScheveningenB = {'name':'AnkervakScheveningenB', 'report': list()  , 'area': Polygon([(4.253992,52.134195),(4.260682,52.125855),(4.247015,52.121877),(4.242040,52.131697)])}

Ankervakken = [Ankervak1, Ankervak2, Ankervak3N, Ankervak3S, Ankervak3E, Ankervak4E, Ankervak4W, Ankervak5, Ankervak6, \
               Ankervak7, Ankervak8, Ankervak_Schouwenbank, Ankervak_ScheveningenA, Ankervak_ScheveningenB]

Hier is de read_csv uitgehaald, die is verplaats naar de iterator een blok daar beneden

In [3]:
# Sprecify the file location here
#filename0 = 'C:\\Users\\marisa\\Documents\\Kustwacht\\testSmall.csv'
#filename0a = 'C:\\Users\\marisa\\Documents\\Kustwacht\\db_20170401_00-00_20170409_23-59_int_30.csv'
filename1 = '/Users/jasper/Documents/Rfiles/IDLab/Ankervakken/Bronnen/db_20170401_00-00_20170409_23-59_int_30.csv.zip'
filename2 = '/Users/jasper/Documents/Rfiles/IDLab/Ankervakken/Bronnen/db_20170410_00-00_20170419_23-59_int_30.csv.zip'
filename3 = '/Users/jasper/Documents/Rfiles/IDLab/Ankervakken/Bronnen/db_20170420_00-00_20170430_23-59_int_30.csv.zip'
filename4 = '/Users/jasper/Documents/Rfiles/IDLab/Ankervakken/Bronnen/db_20170501_00-00_20170531_23-59_int_30.csv.zip'
#filename4 = 'F:\\AIS KWC export april 2017\\db_20170601_00-00_20170630_23-59_int_30.csv.zip'
#df = pd.read_csv(filename1)

Dit is de grote nieuw forloop die inleest, cleaned, kijkt of ze in het ankervak vallen en dan toevoegd aan de juist dict in 'Ankervakken'

In [4]:
%%time
for df in pd.read_csv(filename1, iterator=True, chunksize=1e8):
    # Creation of a new dataframe df_new without the less relevant columns
    systemID = df.iloc[:,0:1]
    name_lat_long = df.iloc[:,6:9]
    imo = df.iloc[:,33:34]
    t_init = df.iloc[:,1:2]
    t_update = df.iloc[:,2:3]
    mmsi = df.iloc[:,5:6]
    ves = df.iloc[:,40:41]
    des = df.iloc[:,30:31]
    speed = df.iloc[:,20:21]
    heading = df.iloc[:,21:22]
    length = df.iloc[:,11:12]
    navstatus = df.iloc[:,14:15]

    df_new = pd.concat([systemID, name_lat_long, imo, mmsi, ves, des, speed, heading, length, navstatus ,t_init, t_update, ],axis=1)
    df_new.columns = ['SystemID', 'Name', 'Lat', 'Lon', 'IMO', 'MMSI', 'Schiptype', 'Destination', 'Speed', 'Heading', 'Length', "NavStatus", 'Starttime', 'Updatetime']
    
    df_new = df_new[np.isfinite(df_new['MMSI'])]
    df_new['Starttime'] = df_new['Starttime'].astype('datetime64[ns]')
    df_new['Updatetime'] = df_new['Updatetime'].astype('datetime64[ns]')
    
    for n in range(0, len(df_new)):
        la = df_new.iloc[n,2]
        lo = df_new.iloc[n,3]
        coordAsPoint = Point(lo, la)
        for avak in Ankervakken:
            if(avak['area'].contains(coordAsPoint)):
                avak['report'].append(df_new.iloc[n,:])

CPU times: user 44min 2s, sys: 1min 6s, total: 45min 9s
Wall time: 2h 10min 27s

Onderstaan schrijven we de dicts om naar dataframes en voegen de naam van de ankervakken toe

In [20]:
%%time
for avak in Ankervakken:
#    print(avak)
    labels = ['SystemID', 'Name', 'Lat', 'Lon', 'IMO', 'MMSI', 'Schiptype', 'Destination', 'Speed', 'Heading', 'Length', "NavStatus", 'Starttime', 'Updatetime']
    avak['report'] = pd.DataFrame.from_records([s.to_dict() for s in avak['report']])
    
    avak['report']['ankervak'] = avak['name']

CPU times: user 1min 3s, sys: 2.88 s, total: 1min 5s
Wall time: 1min 4s

In [21]:
#%%time
#het toevoegen van alle geselecteerde schepen naar 1 dict en die sorteren op Updatetime
AllSchipinankervak = pd.DataFrame()
for dframe in Ankervakken:
    AllSchipinankervak= AllSchipinankervak.append(dframe['report'], ignore_index = True, sort = False)

AllSchipinankervak.sort_values('Updatetime')

,Destination,Heading,IMO,Lat,Length,Lon,MMSI,Name,NavStatus,Schiptype,Speed,Starttime,SystemID,Updatetime,ankervak
35733,NaN,NaN,NaN,51.918339,292.0,2.911590,636017910.0,MOUNT MERU,1.0,NaN,0.0,2017-04-30 20:57:23.336,2.017043e+18,2017-05-01 00:00:02.325,Ankervak2
35732,ROTTERDAM,NaN,9379727.0,51.932968,400.0,2.928290,477127100.0,NEW FRONTIER,1.0,80.0,0.0,2017-04-30 19:36:11.332,2.017043e+18,2017-05-01 00:00:02.325,Ankervak2
208591,SCHEVENINGEN,92.0,9085182.0,52.019580,23.3,3.553714,244399000.0,UK149 STELLA MARIS,7.0,30.0,2.5,2017-04-30 05:25:17.801,2.017043e+18,2017-05-01 00:00:02.325,Ankervak3E
213706,NaN,NaN,NaN,51.911491,269.5,3.500210,232829000.0,LOCH RANNOCH,1.0,NaN,0.0,2017-04-30 18:27:53.331,2.017043e+18,2017-05-01 00:00:02.325,Ankervak4W
1243742,ANTWERP,NaN,9253210.0,51.782700,213.9,3.336530,247100300.0,GRANDE BUENOS AIRES,1.0,70.0,0.0,2017-04-30 11:03:47.314,2.017043e+18,2017-05-01 00:00:02.325,AnkervakSchouwenbank
1243741,VLISSINGEN,NaN,9001837.0,51.754650,87.9,3.314560,261509000.0,PROGRES,1.0,70.0,0.0,2017-04-29 00:33:11.328,2.017043e+18,2017-05-01 00:00:02.325,AnkervakSchouwenbank
518764,ROTTERDAM,126.5,9327205.0,52.145343,92.8,3.709178,215964000.0,TROY,0.0,80.0,0.5,2017-04-30 20:12:11.802,2.017043e+18,2017-05-01 00:00:02.796,Ankervak5
518766,MOERDIJK,180.5,9618848.0,52.176924,76.3,3.569130,305793000.0,RHOGAS,1.0,80.0,0.2,2017-04-30 18:53:41.320,2.017043e+18,2017-05-01 00:00:05.786,Ankervak5
518767,NaN,NaN,NaN,52.136860,37.4,3.733070,305981000.0,LISA LEHMANN,1.0,NaN,0.0,2017-04-30 19:09:53.788,2.017043e+18,2017-05-01 00:00:05.786,Ankervak5
213707,FOR ORDER,NaN,9372652.0,51.927361,129.9,3.590710,219015298.0,TARNBRIS,1.0,80.0,0.0,2017-04-23 02:18:30.793,2.017042e+18,2017-05-01 00:00:05.786,Ankervak4W
518765,STURE NORWAY,NaN,9291262.0,52.171959,253.9,3.628870,311816000.0,MATTERHORN SPIRIT,1.0,80.0,0.0,2017-04-30 18:53:38.803,2.017043e+18,2017-05-01 00:00:05.786,Ankervak5
1180400,AMSTERDAM,NaN,9233595.0,52.426498,225.0,4.018630,477817800.0,HAI JING,1.0,70.0,0.0,2017-04-30 23:53:57.304,2.017043e+18,2017-05-01 00:00:06.283,Ankervak7
518768,ROTTERDAM,44.6,9299898.0,52.140364,250.0,3.613344,240335000.0,PELAGOS,1.0,80.0,0.2,2017-04-30 21:46:56.786,2.017043e+18,2017-05-01 00:00:08.783,Ankervak5
518770,ROTTERDAM,NaN,9374727.0,52.170479,89.8,3.731800,210803000.0,FRAKT SUND,1.0,70.0,0.0,2017-04-30 18:49:02.799,2.017043e+18,2017-05-01 00:00:11.786,Ankervak5
518769,ROTTERDAM,NaN,9527623.0,52.121792,128.9,3.701260,248621000.0,MISSISSIPPI STAR,1.0,80.0,0.0,2017-04-30 15:56:23.801,2.017043e+18,2017-05-01 00:00:11.786,Ankervak5
213708,NaN,NaN,NaN,51.902580,224.6,3.473580,239746000.0,CAPTAIN DIAMANTIS,1.0,NaN,0.0,2017-04-30 21:33:02.314,2.017043e+18,2017-05-01 00:00:14.328,Ankervak4W
1243743,GHENT,NaN,9155987.0,51.760860,98.6,3.298180,229025000.0,KATRIN,1.0,70.0,0.0,2017-04-30 03:27:13.788,2.017043e+18,2017-05-01 00:00:17.326,AnkervakSchouwenbank
1897001,NL SCH,NaN,9518244.0,52.171310,35.0,4.217060,246134000.0,KLAVERBANK,1.0,70.0,0.0,2017-04-30 17:43:54.300,2.017043e+18,2017-05-01 00:00:18.296,AnkervakScheveningenA
1243744,STEENBANK,255.1,9498274.0,51.763961,185.5,3.332485,229013000.0,RODOPI,1.0,70.0,0.2,2017-04-28 14:09:44.786,2.017043e+18,2017-05-01 00:00:20.311,AnkervakSchouwenbank
518771,NaN,NaN,NaN,52.153370,183.6,3.574340,538090513.0,SINGLE,1.0,NaN,0.0,2017-04-30 20:07:08.321,2.017043e+18,2017-05-01 00:00:23.319,Ankervak5
213709,ROTTERDAM,NaN,9575321.0,51.900711,139.6,3.531150,256623000.0,GOBUSTAN,1.0,80.0,0.0,2017-04-30 00:09:47.330,2.017043e+18,2017-05-01 00:00:32.325,Ankervak4W
128218,"ROTTERDAM,NETHERLAND",NaN,9407457.0,51.921741,250.0,3.130980,249747000.0,MATILDA,1.0,80.0,0.0,2017-04-30 20:57:44.319,2.017043e+18,2017-05-01 00:00:32.325,Ankervak3S
213710,ROTTERDAM ANCHORAGE,NaN,9234678.0,51.880878,182.6,3.418120,220562000.0,TORM OHIO,1.0,80.0,0.0,2017-04-30 21:59:14.318,2.017043e+18,2017-05-01 00:00:32.325,Ankervak4W
1243745,STEENBANK,NaN,9566306.0,51.808109,88.9,3.354850,256755000.0,MT SCALI DEL PONTINO,1.0,80.0,0.0,2017-04-29 14:36:29.330,2.017043e+18,2017-05-01 00:00:32.325,AnkervakSchouwenbank
208592,SCHEVENINGEN,91.1,9085182.0,52.019508,15.0,3.554817,244399000.0,UK149 STELLA MARIS,7.0,30.0,2.6,2017-04-30 05:25:17.801,2.017043e+18,2017-05-01 00:00:32.325,Ankervak3E
94045,ROTTERDAM,NaN,9242120.0,51.998699,250.0,3.212180,636091174.0,HS CARMEN,1.0,80.0,0.0,2017-04-30 19:49:35.317,2.017043e+18,2017-05-01 00:00:32.325,Ankervak3N
1243746,ANTWERP,NaN,9467811.0,51.790459,227.5,3.318880,566242000.0,HAFNIA AFRICA,1.0,80.0,0.0,2017-04-30 05:52:23.327,2.017043e+18,2017-05-01 00:00:32.325,AnkervakSchouwenbank
518773,ROTTERDAM,35.9,9299898.0,52.140454,250.0,3.613465,240335000.0,PELAGOS,1.0,80.0,0.3,2017-04-30 21:46:56.786,2.017043e+18,2017-05-01 00:00:32.796,Ankervak5
518772,ROTTERDAM,175.3,9327205.0,52.145114,92.8,3.709192,215964000.0,TROY,0.0,80.0,0.6,2017-04-30 20:12:11.802,2.017043e+18,2017-05-01 00:00:32.796,Ankervak5
1243747,STEENBANK PILOT,250.3,9252278.0,51.781199,85.0,3.314495,235007413.0,WHITCHALLENGER,1.0,80.0,0.2,2017-04-29 08:08:56.331,2.017043e+18,2017-05-01 00:00:35.319,AnkervakSchouwenbank
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1175648,ROTTERDAM,NaN,9344253.0,52.164921,139.6,3.723910,304824000.0,PACHUCA,1.0,70.0,0.0,2017-05-31 22:20:41.786,2.017053e+18,2017-05-31 23:59:08.796,Ankervak5
1175649,NaN,NaN,NaN,52.173660,143.6,3.592390,370711000.0,DREGGEN,1.0,NaN,0.0,2017-05-31 22:06:38.336,2.017053e+18,2017-05-31 23:59:11.325,Ankervak5
1896990,TERNEUZEN,NaN,9534286.0,51.773231,114.3,3.311200,305641000.0,WILSON VOLOS,1.0,70.0,0.0,2017-05-30 06:28:44.335,2.017053e+18,2017-05-31 23:59:14.342,AnkervakSchouwenbank
1896991,ANTWERP,NaN,9216365.0,51.811550,159.2,3.401940,255805806.0,SENTOSA KONTOR,1.0,70.0,0.0,2017-05-31 09:32:53.332,2.017053e+18,2017-05-31 23:59:20.339,AnkervakSchouwenbank
1175650,ROTTERDAM ANCH,232.7,9198654.0,52.145677,200.7,3.634755,244336000.0,DANIEL K,1.0,70.0,0.2,2017-05-31 23:46:02.344,2.017053e+18,2017-05-31 23:59:20.339,Ankervak5
1175651,NL RTM,NaN,9741815.0,52.179069,228.5,3.547130,311000516.0,PRIMERO,1.0,80.0,0.0,2017-05-19 12:15:17.338,2.017052e+18,2017-05-31 23:59:26.343,Ankervak5
1175653,FOR ORDERS,NaN,9518995.0,52.134682,106.4,3.687040,636015582.0,KARKLOE,1.0,70.0,0.0,2017-05-31 23:15:02.344,2.017053e+18,2017-05-31 23:59:26.343,Ankervak5
1175652,ROTERDAM,NaN,9333814.0,52.179081,142.6,3.623880,228330600.0,CHIBERTA,1.0,80.0,0.0,2017-05-31 01:17:11.329,2.017053e+18,2017-05-31 23:59:26.343,Ankervak5
1896992,STEENBANK,58.3,9346926.0,51.789084,95.7,3.336886,244870427.0,CORAL MEDUSA,1.0,80.0,0.2,2017-05-30 20:34:08.328,2.017053e+18,2017-05-31 23:59:29.338,AnkervakSchouwenbank
1896993,STEENBANK,79.5,9346926.0,51.789071,95.7,3.336897,244870427.0,CORAL MEDUSA,1.0,80.0,0.2,2017-05-30 20:34:08.328,2.017053e+18,2017-05-31 23:59:32.337,AnkervakSchouwenbank
1175655,ORDERS,115.3,9360489.0,52.148348,89.8,3.682766,255803360.0,CUERA,1.0,70.0,0.2,2017-05-31 23:54:02.332,2.017053e+18,2017-05-31 23:59:32.337,Ankervak5
1175654,ROTTERDAM ANCH,204.0,9198654.0,52.145524,200.6,3.634665,244336000.0,DANIEL K,1.0,70.0,0.4,2017-05-31 23:46:02.344,2.017053e+18,2017-05-31 23:59:32.337,Ankervak5
518760,NaN,NaN,NaN,51.929199,239.3,3.594120,256431000.0,MINERVA INDIANA,1.0,NaN,0.0,2017-05-28 18:22:17.344,2.017053e+18,2017-05-31 23:59:35.327,Ankervak4W
1175656,FOR ORDER,9.4,9191278.0,52.173965,100.0,3.664071,304010995.0,FULDA,1.0,70.0,0.2,2017-05-31 23:58:29.335,2.017053e+18,2017-05-31 23:59:35.327,Ankervak5
1175657,ROTTERDAM,267.0,9419450.0,52.147049,249.0,3.578694,538006203.0,ADVANTAGE AVENUE,1.0,80.0,0.2,2017-05-31 21:02:20.330,2.017053e+18,2017-05-31 23:59:38.343,Ankervak5
1896995,STEENBANK ANCHORAGE,220.1,9361380.0,51.781701,110.4,3.349556,245977000.0,CITADEL,1.0,70.0,0.6,2017-05-31 16:08:11.342,2.017053e+18,2017-05-31 23:59:38.343,AnkervakSchouwenbank
1896994,FOR ORDERS,234.8,9394519.0,51.796468,145.5,3.328764,235068963.0,EMMY SCHULTE,1.0,80.0,0.2,2017-05-31 14:56:27.299,2.017053e+18,2017-05-31 23:59:38.343,AnkervakSchouwenbank
518761,NaN,NaN,NaN,51.902550,227.5,3.449590,419746000.0,JAG AABHA,1.0,NaN,0.0,2017-05-30 17:08:59.343,2.017053e+18,2017-05-31 23:59:38.343,Ankervak4W
518762,ROTTERDAM,NaN,9490741.0,51.926140,190.4,3.575040,538003541.0,GILLINGHAM,1.0,70.0,0.0,2017-05-31 09:44:50.346,2.017053e+18,2017-05-31 23:59:38.343,Ankervak4W
1896997,BE GNE,121.3,9210335.0,51.824056,107.4,3.378446,273338250.0,GEORGIY USHAKOV,1.0,70.0,0.2,2017-05-31 23:25:53.345,2.017053e+18,2017-05-31 23:59:41.340,AnkervakSchouwenbank
1896996,STEENBANK ANCHORAGE,243.2,9373541.0,51.774698,89.8,3.323903,235059768.0,NICOLE C,1.0,70.0,0.2,2017-05-31 14:05:05.333,2.017053e+18,2017-05-31 23:59:41.340,AnkervakSchouwenbank
1175658,FOR ORDER,NaN,9255270.0,52.123100,168.9,3.694650,266431000.0,BONITO,1.0,80.0,0.0,2017-05-31 14:56:02.330,2.017053e+18,2017-05-31 23:59:44.339,Ankervak5
1896998,STEENBANK,9.5,9361328.0,51.791875,110.4,3.384511,244389000.0,AMBASSADEUR,1.0,70.0,0.2,2017-05-29 06:25:35.344,2.017053e+18,2017-05-31 23:59:44.339,AnkervakSchouwenbank
1175659,ANCHORAGE NO.5,52.2,9696773.0,52.150401,228.5,3.726026,311000306.0,ALFA BALTICA,1.0,80.0,0.2,2017-05-31 22:20:11.786,2.017053e+18,2017-05-31 23:59:44.796,Ankervak5
128217,NaN,139.7,NaN,52.008576,244.1,3.197445,240147000.0,MINERVA HELEN,1.0,NaN,0.2,2017-05-31 23:03:59.344,2.017053e+18,2017-05-31 23:59:50.338,Ankervak3N
1896999,ANTWERPEN,NaN,9242560.0,51.815540,134.8,3.370460,305886000.0,ELBSTRAND,1.0,70.0,0.0,2017-05-31 08:03:14.345,2.017053e+18,2017-05-31 23:59:50.338,AnkervakSchouwenbank
1897000,STEENBANK,NaN,9128685.0,51.812931,95.7,3.392400,355775000.0,GAS PASHA,1.0,80.0,0.0,2017-05-29 03:03:32.343,2.017053e+18,2017-05-31 23:59:53.341,AnkervakSchouwenbank
518763,NaN,198.3,NaN,51.890588,235.4,3.476929,563014500.0,LOWLANDS RISE,1.0,NaN,0.1,2017-05-29 20:19:50.331,2.017053e+18,2017-05-31 23:59:53.341,Ankervak4W
1175660,ROTTERDAM,NaN,9257591.0,52.126541,95.7,3.730790,258430000.0,BERGEN NORDIC,1.0,80.0,0.0,2017-05-31 21:51:17.802,2.017053e+18,2017-05-31 23:59:53.796,Ankervak5
1957512,NL SCE,NaN,9209130.0,52.179691,267.8,4.217780,311092000.0,NAVION OSLO,1.0,80.0,0.0,2017-05-31 23:00:36.299,2.017053e+18,2017-05-31 23:59:54.297,AnkervakScheveningenA

In [22]:
# Het wegschrijven naar 1 dict
writefilename1 = '/Users/jasper/Documents/Rfiles/IDLab/Ankervakken/Bronnen/'+ '20170401-0409.csv'
writefilename2 = '/Users/jasper/Documents/Rfiles/IDLab/Ankervakken/Bronnen/'+ '20170410-0419.csv'
writefilename3 = '/Users/jasper/Documents/Rfiles/IDLab/Ankervakken/Bronnen/'+ '20170420-0430.csv'
writefilename4 = '/Users/jasper/Documents/Rfiles/IDLab/Ankervakken/Bronnen/'+ '20170501-0531.csv'
#writefilename5 = '/Users/jasper/Documents/Rfiles/IDLab/Ankervakken/Bronnen/'+ '20170601-0630.csv'
#print(writefilename4)

In [23]:
AllSchipinankervak.to_csv(writefilename4)

Onderstaande berekening is nog niet zo veel veranderd, wel wordt er gelooped over een andere dataframe, die net even anders aangeroepen wordt, zie comments in  de code

In [24]:
#even de min/max datum-tijd ophalen om in volgens cell goede grenzen te zetten
(min(AllSchipinankervak['Updatetime']), max(AllSchipinankervak['Updatetime']))

(Timestamp('2017-05-01 00:00:02.325000'),
 Timestamp('2017-05-31 23:59:54.297000'))

In [ ]:
%%time
#creation of time range
#goed opletten hier wordt de timerange nog handmatig ingesteld!
#MMDDYYYY!
prng = pd.date_range('05/01/2017 00:00:00', '06/01/2017 00:00:00', freq='5T').tolist()
idx = [np.random.randn(len(prng))]
dftimes = pd.DataFrame(prng, columns=['A'], index=idx)
dftimes['A'] = dftimes['A'].astype('datetime64[ns]')

dfresult = pd.DataFrame()

#deze loop maakt paren met schepen per ankervak
for avak in Ankervakken: #hier staat nu ankervakken
    df_out = avak['report'] # hier moeten we hem herbenoemen om niet de hele code om te schrijven
    if df_out.index.empty: # hier checken we op lege dataframes,
        continue

    mmsi = df_out['MMSI'].unique()
    mmsiDone = set()
    
    #tracker to inform of progress
    print(len(mmsi))
    
    for mnum1 in mmsi:
        df_temp1 = df_out[df_out['MMSI']==mnum1]
        df_new1 = pd.merge_asof(dftimes, df_temp1, left_on = 'A' , right_on='Updatetime', direction='nearest', tolerance=pd.Timedelta('20m'))
        dist_to_vessels = dict()
        dist_to_vessels[mnum1] = dftimes.copy()
        name1 =  df_new1['Name'].unique()
        mmsiDone.add(mnum1)
        
        
        for mnum2 in mmsi:
            if mnum2 == mnum1:
                continue
            if mnum2 in mmsiDone:
                continue
            else:
                df_temp2 = df_out[df_out['MMSI']==mnum2]
                df_new2 = pd.merge_asof(dftimes, df_temp2, left_on = 'A' , right_on='Updatetime', direction='nearest', tolerance=pd.Timedelta('20m'))
                clms = ['time', 'Name1', 'MMSI1', 'Name2', 'MMSI2', 'Distance', 'Ankervak']
                resultTemp = pd.DataFrame(columns= clms)
                distances = []
                name2 = df_new2['Name'].unique()

                for i in range(len(dftimes)):
                    if np.isfinite([df_new1['Lat'][i], df_new1['Lon'][i], df_new2['Lat'][i], df_new2['Lon'][i]]).all():
                        point1 = (df_new1['Lat'][i], df_new1['Lon'][i])
                        point2 = (df_new2['Lat'][i], df_new2['Lon'][i])
                        dist = distance.geodesic(point1, point2).nautical
                        distances.append(dist)
                        line = {'time': df_new1['A'][i], 'Name1': name1[0], 'MMSI1':mnum1, 'Name2': name2[0],\
                                          'MMSI2': mnum2 ,'Distance': dist, 'Ankervak': df_new1['ankervak'][i] }
                        resultTemp = resultTemp.append(line, ignore_index = True)
                        
                if len(distances)>0:
                    if min(distances) < 0.4:
#                     resultTemp.plot('time', 'Distance', title = str(name1[0]) + ' - '+ str(name2[0]))
                        dfresult = pd.concat([dfresult, resultTemp], axis = 0, ignore_index = True)               

# plt.show()

80
138
22
30
28
229
315
103
856

In [14]:
writefilename1 = '/Users/jasper/Documents/Rfiles/IDLab/Ankervakken/Bronnen/'+ 'distances201704010409.csv'
writefilename2 = '/Users/jasper/Documents/Rfiles/IDLab/Ankervakken/Bronnen/'+ 'distances201704100419.csv'
writefilename3 = '/Users/jasper/Documents/Rfiles/IDLab/Ankervakken/Bronnen/'+ 'distances201704200430.csv'
writefilename4 = '/Users/jasper/Documents/Rfiles/IDLab/Ankervakken/Bronnen/'+ 'distances201705010531.csv'
writefilename5 = '/Users/jasper/Documents/Rfiles/IDLab/Ankervakken/Bronnen/'+ 'distances201706010630.csv'

In [15]:
dfresult.to_csv(writefilename4)